/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tebakAngka;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class modul4 extends javax.swing.JFrame {
    private Random random;
    private int targetAcak,kesempatan,Skor;
    private DefaultListModel<String> scoreListModel;

    /**
     * Creates new form modul4
     */
    public modul4() {
        initComponents();
        random = new Random();
        targetAcak =random.nextInt(100)+ 1;
        System.out.println(targetAcak);
        kesempatan = 10;
        scoreListModel = new DefaultListModel<>();
        jList2.setModel(scoreListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        game = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        permainan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        targetTebakan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cek = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Score = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        tebak = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        score = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 204), null, null));

        game.setPreferredSize(new java.awt.Dimension(317, 433));
        game.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(617, 80));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("ANGKA BERAPA AKU?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel5)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        game.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        permainan.setBackground(new java.awt.Color(0, 255, 0));
        permainan.setPreferredSize(new java.awt.Dimension(146, 50));
        permainan.setLayout(new java.awt.GridLayout(3, 2, 0, 20));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Coba Tebak :");
        permainan.add(jLabel2);
        permainan.add(targetTebakan);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Cek :");
        permainan.add(jLabel3);
        permainan.add(cek);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Score :");
        permainan.add(jLabel1);
        permainan.add(Score);

        game.add(permainan, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(617, 70));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 23));

        tebak.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        tebak.setText("TEBAK");
        tebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tebakActionPerformed(evt);
            }
        });
        jPanel5.add(tebak);

        reset.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel5.add(reset);

        game.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("GAME", game);

        score.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 48)); // NOI18N
        jLabel4.setText("SCORE");
        jPanel2.add(jLabel4);

        score.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(611, 300));

        jList2.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 14)); // NOI18N
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        score.add(jPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("SCORE", score);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tebakActionPerformed
        // TODO add your handling code here                                     
    int tebakan = Integer.parseInt(targetTebakan.getText());
    
    if (kesempatan > 0) { // Cek apakah masih ada kesempatan sebelum proses lainnya
        kesempatan--; // kurangi kesempatan di awal pengecekan
        
        if (tebakan > targetAcak) {
            cek.setText("terlalu besar");
        } else if (tebakan < targetAcak) {
            cek.setText("terlalu kecil");
        } else {
            cek.setText("anda berhasil");
            String nama = JOptionPane.showInputDialog(this, "masukkan nama");
            
            Skor = kesempatan * 10;
            scoreListModel.addElement(nama + ": " + Skor);
            Score.setText(String.valueOf(Skor));
            resetGame();
            return; // keluar dari metode agar tidak lanjut ke kode di bawah
        }
        
        // Update skor sementara
        Score.setText(String.valueOf(kesempatan * 10));
    }

    // Periksa jika kesempatan habis setelah pengurangan
    if (kesempatan == 0) {
        JOptionPane.showMessageDialog(this, "Anda gagal! Angka yang benar adalah: " + targetAcak, "Peringatan", JOptionPane.WARNING_MESSAGE);
        resetGame();
    }
    }//GEN-LAST:event_tebakActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        resetGame();
    }//GEN-LAST:event_resetActionPerformed

    private void resetGame() {
        targetAcak = random.nextInt(100) + 1; // Generate angka baru
        kesempatan = 10; // Reset kesempatan
        targetTebakan.setText("");
        cek.setText("");
        Score.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Score;
    private javax.swing.JTextField cek;
    private javax.swing.JPanel game;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel permainan;
    private javax.swing.JButton reset;
    private javax.swing.JPanel score;
    private javax.swing.JTextField targetTebakan;
    private javax.swing.JButton tebak;
    // End of variables declaration//GEN-END:variables
}

